### ISSUE TITLE
Personagem do jogador

### ISSUE THREAD

**Issue by Abel13** [B2-Software/startag#1]
O personagem do jogador tem as ações:

# Monstro

# Patinho

**Comment by lxdre** [comment]
MONSTRO: movimenta, ataca sozinho se chega inimigos perto, patrulhar, cada personagem tem suas skills
inventário: 1 vida caso morrer
construções: castelo do browser e bad guys house
PATINHO: Movimenta, se chega inimigos perto dele ele usa engolir sozinho, manter posição, atacar, patrulhar, engolir, saltar, pimentinha, virar ovo, construir
engolir: engole unidade inimiga - 15 secs cooldown
saltar: salta uma curta distância - 15 secs cooldown
pimentinha: ganha velocidade de movimento por 4 secs - 15 sec cooldown
virar ovo: fica invulneravel a ataques por 5 secs - 30 secs cooldown
construir: canos, castelo da peach, torre de defesa, casa do yoshi, base dos minions
